/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'd10xa' at '14.12.15 20:34' with Gradle 2.7
 *
 * @author d10xa, @date 14.12.15 20:34
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
