/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'd10xa' at '14.12.15 20:34' with Gradle 2.7
 *
 * @author d10xa, @date 14.12.15 20:34
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
